name: baseball
networks:
  baseball-network:
    driver: bridge
volumes:
  mongo-data:
    driver: local
services:
  db:
    image: mongo:8.0.15-noble
    networks:
      - baseball-network
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

  backend:
    image: node:24
    working_dir: /app
    networks:
      - baseball-network
    volumes:
      - ./backend:/app
    restart: unless-stopped
    user: "1000:1000"
    env_file:
      - ./backend/.env
    command: sh -c "npm install && npm run dev"
    depends_on:
      - db
